import { IProduct } from "./types";
import iPhone14 from "public/assets/img/iPhone14.webp";
import GalaxyS23 from "public/assets/img/GalaxyS23.webp";
import Pixel8 from "public/assets/img/Pixel8.webp";

export const mockProducts: IProduct[] = [
  {
    id: 1,
    name: "iPhone 14",
    brand: "Apple",
    price: 999,
    releaseDate: "2023-09-14",
    specs: {
      screen: "6.1-inch OLED",
      processor: "A15 Bionic",
      ram: "6GB",
      storage: "128GB",
      battery: "3115mAh",
    },
    discount: 10,
    imageUrl: iPhone14.src,
    rating: 3.5,
  },
  {
    id: 2,
    name: "Galaxy S23",
    brand: "Samsung",
    price: 899,
    releaseDate: "2023-02-25",
    specs: {
      screen: "6.2-inch AMOLED",
      processor: "Exynos 2200",
      ram: "8GB",
      storage: "256GB",
      battery: "3700mAh",
    },
    discount: 15,
    imageUrl: GalaxyS23.src,
    rating: 4.5,
  },
  {
    id: 3,
    name: "Pixel 8",
    brand: "Google",
    price: 799,
    releaseDate: "2023-10-15",
    specs: {
      screen: "6.3-inch OLED",
      processor: "Google Tensor G2",
      ram: "8GB",
      storage: "128GB",
      battery: "4500mAh",
    },
    discount: 5,
    imageUrl: Pixel8.src,
    rating: 5,
  },
  {
    id: 4,
    name: "Xperia 1 V",
    brand: "Sony",
    price: 949,
    releaseDate: "2023-05-20",
    specs: {
      screen: "6.5-inch OLED",
      processor: "Snapdragon 8 Gen 1",
      ram: "12GB",
      storage: "256GB",
      battery: "4500mAh",
    },
    discount: 20,
    imageUrl: Pixel8.src,
    rating: 4,
  },
  {
    id: 5,
    name: "OnePlus 11",
    brand: "OnePlus",
    price: 749,
    releaseDate: "2023-03-10",
    specs: {
      screen: "6.7-inch AMOLED",
      processor: "Snapdragon 8 Gen 1",
      ram: "8GB",
      storage: "128GB",
      battery: "5000mAh",
    },
    discount: 10,
    imageUrl: iPhone14.src,
    rating: 4.5,
  },
  {
    id: 6,
    name: "Mi 12",
    brand: "Xiaomi",
    price: 699,
    releaseDate: "2023-01-15",
    specs: {
      screen: "6.5-inch AMOLED",
      processor: "Snapdragon 8 Gen 1",
      ram: "8GB",
      storage: "128GB",
      battery: "4600mAh",
    },
    discount: 12,
    imageUrl: Pixel8.src,
    rating: 5,
  },
  {
    id: 7,
    name: "P50 Pro",
    brand: "Huawei",
    price: 799,
    releaseDate: "2023-04-10",
    specs: {
      screen: "6.6-inch OLED",
      processor: "Kirin 9000",
      ram: "8GB",
      storage: "256GB",
      battery: "4360mAh",
    },
    discount: 8,
    imageUrl: GalaxyS23.src,
    rating: 4.5,
  },
  {
    id: 8,
    name: "Find X5",
    brand: "Oppo",
    price: 849,
    releaseDate: "2023-06-20",
    specs: {
      screen: "6.7-inch AMOLED",
      processor: "Snapdragon 8 Gen 1",
      ram: "12GB",
      storage: "256GB",
      battery: "4800mAh",
    },
    discount: 10,
    imageUrl: Pixel8.src,
    rating: 4,
  },
  {
    id: 9,
    name: "Vivo X80",
    brand: "Vivo",
    price: 799,
    releaseDate: "2023-07-15",
    specs: {
      screen: "6.5-inch AMOLED",
      processor: "Dimensity 9000",
      ram: "8GB",
      storage: "128GB",
      battery: "4500mAh",
    },
    discount: 7,
    imageUrl: iPhone14.src,
    rating: 4.5,
  },
  {
    id: 10,
    name: "Redmi Note 12",
    brand: "Xiaomi",
    price: 499,
    releaseDate: "2023-08-10",
    specs: {
      screen: "6.4-inch AMOLED",
      processor: "Snapdragon 778G",
      ram: "6GB",
      storage: "128GB",
      battery: "5000mAh",
    },
    discount: 5,
    imageUrl: GalaxyS23.src,
    rating: 5,
  },
  {
    id: 11,
    name: "Realme GT 2",
    brand: "Realme",
    price: 599,
    releaseDate: "2023-09-05",
    specs: {
      screen: "6.6-inch AMOLED",
      processor: "Snapdragon 888",
      ram: "8GB",
      storage: "128GB",
      battery: "4500mAh",
    },
    discount: 10,
    imageUrl: Pixel8.src,
    rating: 4.5,
  },
  {
    id: 12,
    name: "Nokia X50",
    brand: "Nokia",
    price: 699,
    releaseDate: "2023-10-01",
    specs: {
      screen: "6.5-inch OLED",
      processor: "Snapdragon 765G",
      ram: "6GB",
      storage: "128GB",
      battery: "4500mAh",
    },
    discount: 15,
    imageUrl: iPhone14.src,
    rating: 4,
  },
  {
    id: 13,
    name: "Moto G200",
    brand: "Motorola",
    price: 799,
    releaseDate: "2023-11-20",
    specs: {
      screen: "6.8-inch LCD",
      processor: "Snapdragon 888+",
      ram: "8GB",
      storage: "128GB",
      battery: "5000mAh",
    },
    discount: 10,
    imageUrl: Pixel8.src,
    rating: 4.5,
  },
  {
    id: 14,
    name: "Asus ROG Phone 6",
    brand: "Asus",
    price: 999,
    releaseDate: "2023-12-10",
    specs: {
      screen: "6.78-inch AMOLED",
      processor: "Snapdragon 8 Gen 1",
      ram: "16GB",
      storage: "512GB",
      battery: "6000mAh",
    },
    discount: 5,
    imageUrl: GalaxyS23.src,
    rating: 5,
  },
  {
    id: 15,
    name: "Honor Magic 4",
    brand: "Honor",
    price: 899,
    releaseDate: "2023-01-25",
    specs: {
      screen: "6.76-inch OLED",
      processor: "Snapdragon 8 Gen 1",
      ram: "12GB",
      storage: "256GB",
      battery: "4600mAh",
    },
    discount: 12,
    imageUrl: Pixel8.src,
    rating: 4.5,
  },
  {
    id: 16,
    name: "ZTE Axon 30",
    brand: "ZTE",
    price: 699,
    releaseDate: "2023-02-15",
    specs: {
      screen: "6.92-inch AMOLED",
      processor: "Snapdragon 870",
      ram: "8GB",
      storage: "128GB",
      battery: "4200mAh",
    },
    discount: 10,
    imageUrl: Pixel8.src,
    rating: 4,
  },
  {
    id: 17,
    name: "LG Velvet 2",
    brand: "LG",
    price: 799,
    releaseDate: "2023-03-05",
    specs: {
      screen: "6.8-inch P-OLED",
      processor: "Snapdragon 765G",
      ram: "8GB",
      storage: "128GB",
      battery: "4300mAh",
    },
    discount: 15,
    imageUrl: iPhone14.src,
    rating: 4.5,
  },
  {
    id: 18,
    name: "Lenovo Legion Phone Duel 2",
    brand: "Lenovo",
    price: 999,
    releaseDate: "2023-04-10",
    specs: {
      screen: "6.92-inch AMOLED",
      processor: "Snapdragon 888",
      ram: "12GB",
      storage: "256GB",
      battery: "5500mAh",
    },
    discount: 20,
    imageUrl: GalaxyS23.src,
    rating: 2,
  },
  {
    id: 19,
    name: "Black Shark 5",
    brand: "Xiaomi",
    price: 899,
    releaseDate: "2023-05-20",
    specs: {
      screen: "6.67-inch AMOLED",
      processor: "Snapdragon 870",
      ram: "12GB",
      storage: "256GB",
      battery: "4650mAh",
    },
    discount: 10,
    imageUrl: Pixel8.src,
    rating: 4.5,
  },
  {
    id: 20,
    name: "Meizu 18",
    brand: "Meizu",
    price: 799,
    releaseDate: "2023-06-15",
    specs: {
      screen: "6.2-inch AMOLED",
      processor: "Snapdragon 888",
      ram: "8GB",
      storage: "128GB",
      battery: "4000mAh",
    },
    discount: 5,
    imageUrl: GalaxyS23.src,
    rating: 4.5,
  },
];
